### ISSUE TITLE
The training loss would encounter "nan" value

### ISSUE THREAD

**Issue by FreedStar** [nayeemrizve/TRSSL#2]
Hello, when I run your codes on CIFAR-10 dataset, I find that the training loss obtains the "nan" value. Can you tell me how to solve this problem?

python train.py --dataset cifar10 --lbl-percent 10 --novel-percent 50 --arch resnet18

Epoch: [68 | 200] LR: 0.100000
Training |################################| (1024/1024) Data: 0.075s | Batch: 0.190s | Total: 0:03:14 | ETA: 0:00:01 | Loss: nan
test epoch: 68/ 200. itr:   40/  40. btime: 0.024s.: 100%|██████████████████████████████████████████████████████████████████████████████| 40/40 [00:01<00:00, 38.94it/s]
test epoch: 68/ 200. itr:   20/  20. btime: 0.032s.: 100%|██████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 26.34it/s]
test epoch: 68/ 200. itr:   20/  20. btime: 0.032s. loss: nan. top1: 10.24. top5: 80.46. : 100%|████████████████████████████████████████| 20/20 [00:00<00:00, 26.47it/s]
UncrGen Iter:  186/ 186. Data: 0.270s. Batch: 0.395s.: 100%|██████████████████████████████████████████████████████████████████████████| 186/186 [01:13<00:00,  2.52it/s]
Files already downloaded and verified
Files already downloaded and verified
epoch: 67, acc-seen: 10.24
epoch: 67, acc-novel: 0.0, nmi-novel: 0.0
epoch: 67, acc-all: 10.02, nmi-all: 0.0008095158137027309, best-acc: 10.280000000000001
NaN or Inf found in input tensor.

**Comment by nayeemrizve** [comment]
Thank you very much for expressing your interest in our work. What version of PyTorch are you using? We tested the code before putting it online. But there's a possibility that we might have missed something.

**Comment by FreedStar** [comment]
Thanks for your reply. My torch version is 1.10.2. I have fixed the "nan" problem, which would occur when we use multiple GPUs. But I have another request: could you please share the train and test data folders for your used datasets in google cloud disk?

**Comment by FreedStar** [comment]
We also find that OpenLDN needs very large GPU memory on some datasets, such as Standford Cars and ImageNet100 datasets. So can you give me more training details or optimize the codes? What is your GPU for experiments?

RuntimeError: CUDA out of memory. Tried to allocate 2.30 GiB (GPU 0; 79.10 GiB total capacity; 30.41 GiB already allocated; 1.37 GiB free; 32.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

**Comment by nayeemrizve** [comment]
Responded to this issue at the OpenLDN repository. Therefore, closing it for now.
