### ISSUE TITLE
Dataset utilized

### ISSUE THREAD

**Issue by ascetic-monk** [nayeemrizve/TRSSL#3]
First of all, thanks for your open code! I encounter some issues when running your code. Which ImageNet100 dataset do you utilize in your paper? To my acknowledgment, it seems that the ImageNet100 in ORCA(the baselines) uses different divisions from the published ImageNet100 in Kaggle. Can you post the categories of ImageNet100 in your paper?

**Comment by nayeemrizve** [comment]
Thank you for expressing interest in our work. We have provided the list of ImageNet-100 classes at the following location
https://github.com/nayeemrizve/TRSSL/tree/main/datasets/imagenet_subsets. These classes are the same as the ones used at _SCAN: Learning to Classify Images without Labels; Gansbeke et al. ECCV 2020_ available here: https://github.com/wvangansbeke/Unsupervised-Classification/tree/master/data/imagenet_subsets. Hope this answers your concerns.
