### ISSUE TITLE
question about the results

### ISSUE THREAD

**Issue by sheng-eatamath** [nayeemrizve/TRSSL#4]
Hi, thanks for your great work!
I have some questions:
- about the performance reported in Table 1 and 2, for four datasets (CIFAR and IN), are you assuming the unknown class number?
- about the performance for imbalanced setting, the code in SK algorithm in this repo seems assume the ground-truth imbalance distribution? While your paper uses iterative prior update strategy. Is my understanding correct?
Looking for your reply.

Best regards,

**Comment by nayeemrizve** [comment]
Hello,

Thank you for expressing interest in our work. Following are the responses to your questions.

- Yes, for the results reported in Tables 1 and 2 we assume that the number of unknown classes is known in advance. We report the results with the estimated number of unknown classes in the second last row of Table 3.
- Yes the code we have uploaded to this repo assumes knowledge of ground-truth imbalance distribution (second row of Table 5). 

Hope this answers your questions. Please feel free to reach out if you have any follow-up questions.
